### ISSUE TITLE
Debian arts image?

### ISSUE THREAD

**Issue by davidebangelista** [ruanformigoni/arts#1]
Hello,

From the included files below, I see that ubuntu is used.

If possible, would it be possible to include debian (Bookworm) as an art image?

I would happly create one and support this project!

**Comment by ruanformigoni** [comment]
Hey there! Sure thing, feel free to open a PR. I think the only change required for that is in .gitlab-ci:

```yaml
package-bookworm:
  stage: package
  when: manual
  before_script:
    - apt update && apt -y upgrade
    - apt install -y git wget curl zstd debootstrap e2fsprogs proot fuse2fs xz-utils rsync
    - echo JOB_ID_BUILD_BS_FOCAL=$CI_JOB_ID > build.env
  script:
    # Set dist
    - dist="bookworm"
    # Build
    - ./src/scripts/_build.sh debootstrap "$dist"
    # Set env vars
    - echo "FOCAL_TARBALL=${dist}.tar.xz" >> build.env
  needs:
    - job: build-elf
      artifacts: true
    - job: build-fuse2fs
      artifacts: true
  artifacts:
    paths:
      - ./dist
    reports:
      dotenv: build.env
```

If you run into any problems let me know, creating more debian-based images is in my plans.
